name: CI node API

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main
env:
    NODE_VERSION: 20.x
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Configurando o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'    # Cache de dependências NPM (melhora a velocidade do pipeline)

      # Instalando dependências
      - name: Install dependencies
        run: npm ci

      # Rodando testes
      - name: Run tests
        run: npm run test




