name: CI

on:
 push:
  branches:
   - main
  pull_request:
     branches:
       - main

jobs: 
  lint-and-tests:
    runs-on: ubuntu-latst

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: setup Node.js
       uses: actions/setu-node@v4
       with: 
         node-version: 20.x
         cache: npm
      
     - name: Install depencies
       run: npm ci

     - name: Run linter
       run: npm run lint

     - name: Run tests
       run: npm run test

           